### PR TITLE
Rails5 Update

### PR DESCRIPTION
**Pull request by jlsookiki**
Removed the `alias_method_chain`s since that is being deprecated.  Also forced a version of Rake to allow all tests to pass

### CODE REVIEW

**Comment by inbeom** [comment]
@jlsookiki This is my personal fork of the main repository https://github.com/jashmenn/activeuuid, so you'd better open your PR on the original one.

Also I think these fixes are covered in my PR https://github.com/jashmenn/activeuuid/pull/85. But if there are anything I've missed out, would you start discussions on that thread instead? Thanks.

**Comment by jlsookiki** [comment]
@inbeom I can make a PR to the actual repo that's fine.  I only made this into yours since I forked it off yours.  This just does a slight refactor or yours to remove some final deprecations

**Comment by inbeom** [comment]
@jlsookiki I read https://github.com/jashmenn/activeuuid/pull/86 so now I see that. I am really sorry I missed to notice the base branch of this PR is not `master`.

Can we continue our discussion after I merge #1? I think we can maintain activeuuid before @jashmenn decides working on it again.

**Comment by inbeom** [comment]
@jlsookiki I've done some housekeeping works on this fork so we can start our discussion from now on. Can you open your PR against `master` branch? Thanks a lot!

**Comment by jlsookiki** [comment]
@inbeom sounds good. I'll open it up in a bit

**Pull request closed without merging**
